version: "3.5"

networks:
  dev:

services:
  marketmaker:
    container_name: mm
    hostname: marketmaker
    image: "jessmillar/marketmaker:chaos__947e33e__20221125"
    networks:
      - "dev"
    ports:
      - 7997:8000
  dev-validator:
    container_name: molly
    image: "jessmillar/ta-validator:latest"
    ports:
      - 8001:8000
  redis:
    hostname: redis
    container_name: mm-redis
    image: redis:6-alpine
    networks:
      - "dev"
    ports:
      - "6379:6379"
